apiVersion: 1

datasources:
  - name: MergeStat Postgres
    uid: mergestat-postgres
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 1400
    isDefault: true
    editable: true
