{
 "title": "Trivy",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "Repositories",
    "query": "SELECT repo FROM repos ORDER BY repo"
   },
   {
    "name": "repository_tags",
    "label": "Repository Tags",
    "query": "SELECT DISTINCT value FROM repos, jsonb_array_elements_text(tags) "
   }
  ]
 },
 "panels": [
  {
   "title": "Total Critical Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_vulnerabilities\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nWHERE public.trivy_repo_vulnerabilities.vulnerability_severity = 'CRITICAL'\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\n"
    }
   ]
  },
  {
   "title": "Vulnerability Count by Severity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    vulnerability_severity,\n    COUNT(*) AS total_vulnerabilities\nFROM public.trivy_repo_vulnerabilities \nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 1\nORDER BY 1 DESC\n"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Repo (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    repos.repo,\n    COUNT(case when (vulnerability_severity='UNKNOWN') then 1 else NULL end) as unknown,\n    COUNT(case when (vulnerability_severity='LOW') then 1 else NULL end) as low,\n    COUNT(case when (vulnerability_severity='MEDIUM') then 1 else NULL end) as medium,\n    COUNT(case when (vulnerability_severity='HIGH') then 1 else NULL end) as high,\n    COUNT(case when (vulnerability_severity='CRITICAL') then 1 else NULL end) as critical,\n    COUNT(*) AS total_vulnerabilities\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (repos.repo)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nGROUP BY 1\nORDER BY 7 DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Critical Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    public.repos.repo,\n    public.trivy_repo_vulnerabilities.vulnerability_id AS \"ID\",\n    public.trivy_repo_vulnerabilities.vulnerability_title AS \"Title\",\n    public.trivy_repo_vulnerabilities.vulnerability->>'PublishedDate' AS \"Published Date\",\n    public.trivy_repo_vulnerabilities.vulnerability->>'FixedVersion' AS \"Fixed Version\",\n    public.trivy_repo_vulnerabilities.vulnerability_installed_version AS \"Installed Version\"\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nWHERE public.trivy_repo_vulnerabilities.vulnerability_severity = 'CRITICAL'\nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.repos.repo)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n    public.repos.repo,\n    public.trivy_repo_vulnerabilities.vulnerability_id AS \"ID\",\n    public.trivy_repo_vulnerabilities.vulnerability_title AS \"Title\",\n    public.trivy_repo_vulnerabilities.vulnerability_severity AS \"Severity\",\n    JSON_EXTRACT_PATH_TEXT(public.trivy_repo_vulnerabilities.vulnerability::json, variadic '{PublishedDate}') AS \"Published Date\",\n    JSON_EXTRACT_PATH_TEXT(public.trivy_repo_vulnerabilities.vulnerability::json, variadic '{FixedVersion}') AS \"Fixed Version\",\n    public.trivy_repo_vulnerabilities.vulnerability_installed_version AS \"Vulnerability Installed Version\"\nFROM public.trivy_repo_vulnerabilities\nINNER JOIN public.repos ON public.repos.id = public.trivy_repo_vulnerabilities.repo_id\nWHERE (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.repos.repo)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nORDER BY 1"
    }
   ]
  }
 ]
}